### Obtener todos los alumnos registrados.
GET http://localhost:3000/alumnos

###
### Obtener un alumno específico por su ID.
GET http://localhost:3000/alumnos/2

###
### Crear un alumno enviando sus datos en formato JSON.
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 3,
    "nombre": "Lucía",
    "carrera": "Programación"
}
###
### Actualizar los datos del alumno cuyo ID se indica en la URL.
PUT http://localhost:3000/alumnos/2
Content-Type: application/json

{
    "id": 2,
    "nombre": "Juan Perez",
    "carrera": "Programación"
}

###
### Eliminar el alumno cuyo ID se indica en la URL.
DELETE http://localhost:3000/alumnos/2